### ISSUE TITLE
Using ENV vars instead of a config yaml file.

### ISSUE THREAD

**Issue by bgruening** [bgruening/docker-ipython-notebook#21]
If the amount of variables is small enough, consider to to use ENV variables instead of the yaml file.

**Comment by erasche** [comment]
Amount of variables has remained small, v0.2 should use ENV.

**Comment by erasche** [comment]
Env variables:


Name | Use 
--- | ---
`debug` | More logging, don't rm -rf the folder when done (#32)
`galaxy_web_port` | Originally `galaxy_paster_port` (#30)
`notebook_password` | 
`cors_origin` | Expected final browser URL for accessing ipynb
`docker_port` | used to unique-ify routes internally since rewriting URLs in every single call/response is a huge overhead for the nodejs proxy.
